"""Persistence and lexical search over chunks.

Uses SQLAlchemy Core with the schema resolved **at call time** rather than ORM models,
for a specific reason: `AM-27` r1 puts the assist tables in a separate schema, and in a
test run that schema is derived per process (``<run>_assist``, so concurrent suites
cannot collide as they did under `F-4`). A declarative model fixes its schema at import
time, which is before `conftest` has decided what it is. Core tables built per call have
no such problem, and the locked `Base.metadata` stays untouched — which is what keeps
`test_locked_schema_columns.py` passing unmodified, `AM-27` r2's stated evidence.

--------------------------------------------------------------------------
This is lexical search, and it is NOT BM25
--------------------------------------------------------------------------
PostgreSQL full-text search with `ts_rank`, plus trigram similarity. Real BM25 in
PostgreSQL needs an extension that is not authorized (`AM-26`). Worth stating precisely
wherever this is described, because "BM25" appears in the product vision and specifying
against a ranking function the stack does not have would mislead whoever tunes it.

Two signals rather than one, because they fail differently on legal text: `tsvector`
stems and so matches paraphrase, but mangles "17.2" and party names; trigram matches
those literally but has no notion of word meaning. Results are ordered by both, and
deliberately **not** fused into a single weighted score — a weight would be an invented
number, and rank fusion belongs with the vector half in A3/A4 where it can be measured.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from sqlalchemy import Column, MetaData, Table, text
from sqlalchemy.orm import Session as DBSession

from legalmind import config
from legalmind.assist.chunking import (
    CHUNKING_ALGORITHM_VERSION,
    Chunk,
    leading_section_ref,
)


def _chunks_table(schema: str) -> Table:
    """A Core handle on `<assist>.chunks`, built for this call's schema.

    Only the columns this module writes are declared; `content_tsv` is generated by the
    database and `created_at` defaults there, so neither is ever written from here.
    """
    from sqlalchemy import BigInteger, Integer, String, Text
    from sqlalchemy.dialects.postgresql import UUID as PGUUID

    return Table(
        "chunks", MetaData(),
        Column("id", PGUUID(as_uuid=True), primary_key=True),
        Column("document_version_id", PGUUID(as_uuid=True)),
        Column("evidence_id", PGUUID(as_uuid=True)),
        Column("ordinal", Integer),
        Column("content", Text),
        Column("start_offset", BigInteger),
        Column("end_offset", BigInteger),
        Column("chunking_algorithm_version", String(64)),
        schema=schema,
    )



# pg_trgm's functions live in whatever schema the extension was installed into, and the
# test harness runs with `search_path` pointed at a private per-run schema (`F-4`), so an
# unqualified `similarity(...)` does not resolve. Qualified from a live lookup rather
# than widening the path — the same choice the migration makes for `gin_trgm_ops`, and
# for the same reason: a wider path gives every unqualified lookup a fallback into a
# shared schema.
#
# Cached because it is a property of the installation, not of the query. A process talks
# to one database, and moving an installed extension between schemas is not something
# that happens under a running application.
_TRGM_SCHEMA: str | None = None


def _trgm_schema(db: DBSession) -> str:
    global _TRGM_SCHEMA
    if _TRGM_SCHEMA is None:
        found = db.execute(text(
            "SELECT n.nspname FROM pg_extension e "
            "JOIN pg_namespace n ON n.oid = e.extnamespace "
            "WHERE e.extname = 'pg_trgm'")).scalar()
        if not found:
            raise RuntimeError(
                "pg_trgm is not installed; the assist migration creates it and "
                "lexical search depends on it")
        _TRGM_SCHEMA = str(found)
    return _TRGM_SCHEMA


@dataclass(frozen=True)
class SearchHit:
    """One lexical match, with its provenance resolved through the evidence row.

    `retrieval_score` is a property of *this query*, not of the chunk — which is why it
    is returned here and never stored on the row (storing it would make a per-question
    number look like a permanent property of the document). It is a **retrieval score**
    and is never rendered to a user as legal confidence: `AI-03` locked item 16.
    """

    chunk_id: UUID
    evidence_id: UUID
    content: str
    page_number: int | None
    section_number: str | None
    section_title: str | None
    source_type: str
    retrieval_score: float

    @property
    def section_ref(self) -> str | None:
        """The clause this hit belongs to, for a citation.

        Prefers the evidence row's own `section_number`, and falls back to the number
        the chunk's text opens with. The fallback matters far more than it looks:
        measured on the real supplied documents, PyMuPDF emits no blank lines, so the
        parser produces one page-sized evidence row per page and **2 of 59 rows carried
        a section number**. Reading it from the chunk's leading clause marker raises
        that to 300 of 341 chunks.

        Derived, never stored — a pure function of text already selected, so it cannot
        drift, and `AM-27` r4's bar on independent provenance is untouched.
        """
        return self.section_number or leading_section_ref(self.content)


def count_chunks(db: DBSession, document_version_id: UUID) -> int:
    schema = config.assist_schema()
    return db.execute(
        text(f'SELECT count(*) FROM "{schema}".chunks '
             'WHERE document_version_id = :dv'),
        {"dv": document_version_id},
    ).scalar_one()


def write_chunks(db: DBSession, document_version_id: UUID,
                 chunks: list[Chunk]) -> int:
    """Insert chunks for a document version. Returns the number written.

    Does not commit — the caller owns the transaction boundary, matching the ingestion
    layer's own convention (locked 43.26: the request dependency commits on success and
    rolls back on failure).
    """
    if not chunks:
        return 0
    import uuid as _uuid

    table = _chunks_table(config.assist_schema())
    db.execute(table.insert(), [
        {
            "id": _uuid.uuid4(),
            "document_version_id": document_version_id,
            "evidence_id": c.evidence_id,
            "ordinal": c.ordinal,
            "content": c.content,
            "start_offset": c.start_offset,
            "end_offset": c.end_offset,
            "chunking_algorithm_version": CHUNKING_ALGORITHM_VERSION,
        }
        for c in chunks
    ])
    return len(chunks)


def delete_chunks(db: DBSession, document_version_id: UUID) -> int:
    """Remove a document version's chunks. Returns the number removed.

    ⚠️ This cascades to `answer_citations`, so a re-index silently invalidates any
    citation already recorded against a removed chunk. That is why re-indexing requires an
    explicit instruction rather than happening on every upload — see
    `legalmind.assist.indexing`.
    """
    schema = config.assist_schema()
    # RETURNING rather than `rowcount`: the Core result's rowcount is not typed as
    # available on every driver, and counting the returned ids is exact.
    removed = db.execute(
        text(f'DELETE FROM "{schema}".chunks WHERE document_version_id = :dv '
             'RETURNING id'),
        {"dv": document_version_id},
    ).all()
    return len(removed)


def search_chunks(db: DBSession, *, document_version_id: UUID, query: str,
                  limit: int = 20) -> list[SearchHit]:
    """Lexical search within ONE authorized document version.

    **`AM-25` r6 — authorization before retrieval, inside the query.** The scope is a
    `document_version_id` the caller has already authorized through the existing
    `Guard`, and it is applied as a `WHERE` clause on the candidate set rather than as a
    filter over results. That ordering is the point: post-filtering would let result
    counts, ranking or latency reveal the existence of a chunk in a document the
    requester may not read, which is precisely the enumeration oracle r7 forbids and
    which `API-10`'s byte-identical-404 discipline exists to close.

    The signature takes a single authorized id rather than an open query plus a filter
    for the same reason — a caller cannot forget to scope this.

    Provenance is joined from `document_evidence` rather than read from the chunk row:
    `AM-27` r4 keeps the chunk free of independent provenance, so the page and section a
    citation displays come from the authoritative evidence row every time.
    """
    if not query or not query.strip():
        return []

    schema = config.assist_schema()
    trgm = _trgm_schema(db)
    rows = db.execute(text(f"""
        SELECT c.id,
               c.evidence_id,
               c.content,
               e.page_number,
               e.section_number,
               e.section_title,
               e.source_type,
               ts_rank(c.content_tsv, websearch_to_tsquery('english', :q)) AS rank,
               {trgm}.similarity(c.content, :q)                            AS sim
          FROM "{schema}".chunks c
          JOIN document_evidence e ON e.id = c.evidence_id
         WHERE c.document_version_id = :dv
           AND (c.content_tsv @@ websearch_to_tsquery('english', :q)
                OR c.content ILIKE '%%' || :q || '%%')
         ORDER BY rank DESC, sim DESC, c.ordinal ASC
         LIMIT :lim
    """), {"dv": document_version_id, "q": query.strip(), "lim": limit}).all()

    return [
        SearchHit(
            chunk_id=r[0], evidence_id=r[1], content=r[2], page_number=r[3],
            section_number=r[4], section_title=r[5],
            source_type=str(r[6]),
            # `ts_rank` is 0 for a row matched only by the literal branch. Reporting
            # the trigram similarity there is more honest than reporting zero, which
            # would read as "matched nothing".
            retrieval_score=float(r[7]) if r[7] else float(r[8] or 0.0),
        )
        for r in rows
    ]
