"""Persistence and lexical search over chunks.

Uses SQLAlchemy Core with the schema resolved **at call time** rather than ORM models,
for a specific reason: `AM-27` r1 puts the assist tables in a separate schema, and in a
test run that schema is derived per process (``<run>_assist``, so concurrent suites
cannot collide as they did under `F-4`). A declarative model fixes its schema at import
time, which is before `conftest` has decided what it is. Core tables built per call have
no such problem, and the locked `Base.metadata` stays untouched — which is what keeps
`test_locked_schema_columns.py` passing unmodified, `AM-27` r2's stated evidence.

--------------------------------------------------------------------------
This is lexical search, and it is NOT BM25
--------------------------------------------------------------------------
PostgreSQL full-text search with `ts_rank`, plus trigram similarity. Real BM25 in
PostgreSQL needs an extension that is not authorized (`AM-26`). Worth stating precisely
wherever this is described, because "BM25" appears in the product vision and specifying
against a ranking function the stack does not have would mislead whoever tunes it.

Two signals rather than one, because they fail differently on legal text: `tsvector`
stems and so matches paraphrase, but mangles "17.2" and party names; trigram matches
those literally but has no notion of word meaning. Results are ordered by both, and
deliberately **not** fused into a single weighted score — a weight would be an invented
number, and rank fusion belongs with the vector half in A3/A4 where it can be measured.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from sqlalchemy import Column, MetaData, Table, text
from sqlalchemy.orm import Session as DBSession

from legalmind import config
from legalmind.assist.chunking import (
    CHUNKING_ALGORITHM_VERSION,
    Chunk,
    leading_section_ref,
)


def _chunks_table(schema: str) -> Table:
    """A Core handle on `<assist>.chunks`, built for this call's schema.

    Only the columns this module writes are declared; `content_tsv` is generated by the
    database and `created_at` defaults there, so neither is ever written from here.
    """
    from sqlalchemy import BigInteger, Integer, String, Text
    from sqlalchemy.dialects.postgresql import UUID as PGUUID

    return Table(
        "chunks", MetaData(),
        Column("id", PGUUID(as_uuid=True), primary_key=True),
        Column("document_version_id", PGUUID(as_uuid=True)),
        Column("evidence_id", PGUUID(as_uuid=True)),
        Column("ordinal", Integer),
        Column("content", Text),
        Column("start_offset", BigInteger),
        Column("end_offset", BigInteger),
        Column("chunking_algorithm_version", String(64)),
        schema=schema,
    )



# pg_trgm's functions live in whatever schema the extension was installed into, and the
# test harness runs with `search_path` pointed at a private per-run schema (`F-4`), so an
# unqualified `similarity(...)` does not resolve. Qualified from a live lookup rather
# than widening the path — the same choice the migration makes for `gin_trgm_ops`, and
# for the same reason: a wider path gives every unqualified lookup a fallback into a
# shared schema.
#
# Cached because it is a property of the installation, not of the query. A process talks
# to one database, and moving an installed extension between schemas is not something
# that happens under a running application.
_TRGM_SCHEMA: str | None = None
_VECTOR_SCHEMA: str | None = None


def vector_schema(db: DBSession) -> str:
    """The schema the pgvector extension is installed into.

    Same story as `_trgm_schema` below: the extension's objects — the type AND its
    operators — live wherever the extension was installed, the harness pins
    `search_path` to a private per-run schema, and qualifying beats widening the
    path. An operator needs `OPERATOR("schema".<=>)` syntax, so the schema itself is
    the reusable answer.
    """
    global _VECTOR_SCHEMA
    if _VECTOR_SCHEMA is None:
        found = db.execute(text(
            "SELECT n.nspname FROM pg_extension e "
            "JOIN pg_namespace n ON n.oid = e.extnamespace "
            "WHERE e.extname = 'vector'")).scalar()
        if not found:
            raise RuntimeError(
                "pgvector is not installed; it is a deployment precondition "
                "(see legalmind.deploy.preflight)")
        _VECTOR_SCHEMA = str(found)
    return _VECTOR_SCHEMA


def vector_type(db: DBSession) -> str:
    """The schema-qualified `vector` type name, e.g. ``"public".vector``."""
    return f'"{vector_schema(db)}".vector'


def _trgm_schema(db: DBSession) -> str:
    global _TRGM_SCHEMA
    if _TRGM_SCHEMA is None:
        found = db.execute(text(
            "SELECT n.nspname FROM pg_extension e "
            "JOIN pg_namespace n ON n.oid = e.extnamespace "
            "WHERE e.extname = 'pg_trgm'")).scalar()
        if not found:
            raise RuntimeError(
                "pg_trgm is not installed; the assist migration creates it and "
                "lexical search depends on it")
        _TRGM_SCHEMA = str(found)
    return _TRGM_SCHEMA


@dataclass(frozen=True)
class SearchHit:
    """One lexical match, with its provenance resolved through the evidence row.

    `retrieval_score` is a property of *this query*, not of the chunk — which is why it
    is returned here and never stored on the row (storing it would make a per-question
    number look like a permanent property of the document). It is a **retrieval score**
    and is never rendered to a user as legal confidence: `AI-03` locked item 16.
    """

    chunk_id: UUID
    evidence_id: UUID
    content: str
    page_number: int | None
    section_number: str | None
    section_title: str | None
    source_type: str
    retrieval_score: float

    @property
    def section_ref(self) -> str | None:
        """The clause this hit belongs to, for a citation.

        Prefers the evidence row's own `section_number`, and falls back to the number
        the chunk's text opens with. The fallback matters far more than it looks:
        measured on the real supplied documents, PyMuPDF emits no blank lines, so the
        parser produces one page-sized evidence row per page and **2 of 59 rows carried
        a section number**. Reading it from the chunk's leading clause marker raises
        that to 300 of 341 chunks.

        Derived, never stored — a pure function of text already selected, so it cannot
        drift, and `AM-27` r4's bar on independent provenance is untouched.
        """
        return self.section_number or leading_section_ref(self.content)


def count_chunks(db: DBSession, document_version_id: UUID) -> int:
    schema = config.assist_schema()
    return db.execute(
        text(f'SELECT count(*) FROM "{schema}".chunks '
             'WHERE document_version_id = :dv'),
        {"dv": document_version_id},
    ).scalar_one()


def write_chunks(db: DBSession, document_version_id: UUID,
                 chunks: list[Chunk]) -> int:
    """Insert chunks for a document version. Returns the number written.

    Does not commit — the caller owns the transaction boundary, matching the ingestion
    layer's own convention (locked 43.26: the request dependency commits on success and
    rolls back on failure).
    """
    if not chunks:
        return 0
    import uuid as _uuid

    table = _chunks_table(config.assist_schema())
    db.execute(table.insert(), [
        {
            "id": _uuid.uuid4(),
            "document_version_id": document_version_id,
            "evidence_id": c.evidence_id,
            "ordinal": c.ordinal,
            "content": c.content,
            "start_offset": c.start_offset,
            "end_offset": c.end_offset,
            "chunking_algorithm_version": CHUNKING_ALGORITHM_VERSION,
        }
        for c in chunks
    ])
    return len(chunks)


def delete_chunks(db: DBSession, document_version_id: UUID) -> int:
    """Remove a document version's chunks. Returns the number removed.

    ⚠️ This cascades to `answer_citations`, so a re-index silently invalidates any
    citation already recorded against a removed chunk. That is why re-indexing requires an
    explicit instruction rather than happening on every upload — see
    `legalmind.assist.indexing`.
    """
    schema = config.assist_schema()
    # RETURNING rather than `rowcount`: the Core result's rowcount is not typed as
    # available on every driver, and counting the returned ids is exact.
    removed = db.execute(
        text(f'DELETE FROM "{schema}".chunks WHERE document_version_id = :dv '
             'RETURNING id'),
        {"dv": document_version_id},
    ).all()
    return len(removed)


def search_chunks(db: DBSession, *, document_version_id: UUID, query: str,
                  limit: int = 20) -> list[SearchHit]:
    """Lexical search within ONE authorized document version.

    **`AM-25` r6 — authorization before retrieval, inside the query.** The scope is a
    `document_version_id` the caller has already authorized through the existing
    `Guard`, and it is applied as a `WHERE` clause on the candidate set rather than as a
    filter over results. That ordering is the point: post-filtering would let result
    counts, ranking or latency reveal the existence of a chunk in a document the
    requester may not read, which is precisely the enumeration oracle r7 forbids and
    which `API-10`'s byte-identical-404 discipline exists to close.

    The signature takes a single authorized id rather than an open query plus a filter
    for the same reason — a caller cannot forget to scope this.

    Provenance is joined from `document_evidence` rather than read from the chunk row:
    `AM-27` r4 keeps the chunk free of independent provenance, so the page and section a
    citation displays come from the authoritative evidence row every time.
    """
    if not query or not query.strip():
        return []

    schema = config.assist_schema()
    trgm = _trgm_schema(db)
    rows = db.execute(text(f"""
        SELECT c.id,
               c.evidence_id,
               c.content,
               e.page_number,
               e.section_number,
               e.section_title,
               e.source_type,
               ts_rank(c.content_tsv, websearch_to_tsquery('english', :q)) AS rank,
               {trgm}.similarity(c.content, :q)                            AS sim
          FROM "{schema}".chunks c
          JOIN document_evidence e ON e.id = c.evidence_id
         WHERE c.document_version_id = :dv
           AND (c.content_tsv @@ websearch_to_tsquery('english', :q)
                OR c.content ILIKE '%%' || :q || '%%')
         ORDER BY rank DESC, sim DESC, c.ordinal ASC
         LIMIT :lim
    """), {"dv": document_version_id, "q": query.strip(), "lim": limit}).all()

    return [
        SearchHit(
            chunk_id=r[0], evidence_id=r[1], content=r[2], page_number=r[3],
            section_number=r[4], section_title=r[5],
            source_type=str(r[6]),
            # `ts_rank` is 0 for a row matched only by the literal branch. Reporting
            # the trigram similarity there is more honest than reporting zero, which
            # would read as "matched nothing".
            retrieval_score=float(r[7]) if r[7] else float(r[8] or 0.0),
        )
        for r in rows
    ]


# ==========================================================================
# Embeddings — written at index time, searched at query time
# ==========================================================================
def register_embedding_model(db: DBSession, *, name: str, version: str,
                             dimensions: int, checksum: str) -> UUID:
    """Idempotently register a model in the `embedding_models` registry.

    `AM-26` r4: the version is recorded against every answer — which starts here, by
    every stored vector carrying a foreign key to the exact model row that produced
    it. Re-registration of the same name+version returns the existing id.
    """
    import uuid as _uuid

    schema = config.assist_schema()
    existing = db.execute(text(
        f'SELECT id FROM "{schema}".embedding_models '
        'WHERE name = :n AND version = :v'), {"n": name, "v": version}).scalar()
    if existing:
        return existing
    model_id = _uuid.uuid4()
    db.execute(text(f"""
        INSERT INTO "{schema}".embedding_models (id, name, version, dimensions, checksum)
        VALUES (:i, :n, :v, :d, :c)
    """), {"i": model_id, "n": name, "v": version, "d": dimensions, "c": checksum})
    return model_id


def write_embeddings(db: DBSession, *, chunk_ids: list[UUID],
                     vectors: list[list[float]], embedding_model_id: UUID) -> int:
    """Store one vector per chunk for one model. Returns the number written.

    The vector crosses the wire as a text literal cast in SQL — the application
    deliberately carries no pgvector Python dependency, so this is the whole binding.
    """
    import uuid as _uuid

    if not chunk_ids:
        return 0
    schema = config.assist_schema()
    vtype = vector_type(db)
    rows = [{"i": _uuid.uuid4(), "c": cid,
             "m": embedding_model_id,
             "v": "[" + ",".join(f"{x:.6f}" for x in vec) + "]"}
            for cid, vec in zip(chunk_ids, vectors, strict=True)]
    db.execute(text(f"""
        INSERT INTO "{schema}".chunk_embeddings
            (id, chunk_id, embedding_model_id, embedding)
        VALUES (:i, :c, :m, CAST(:v AS {vtype}))
        ON CONFLICT ON CONSTRAINT uq_chunk_embeddings_chunk_model DO NOTHING
    """), rows)
    return len(rows)


def count_embeddings(db: DBSession, document_version_id: UUID) -> int:
    schema = config.assist_schema()
    return db.execute(text(f"""
        SELECT count(*) FROM "{schema}".chunk_embeddings e
          JOIN "{schema}".chunks c ON c.id = e.chunk_id
         WHERE c.document_version_id = :dv
    """), {"dv": document_version_id}).scalar_one()


# ==========================================================================
# Hybrid retrieval with the calibrated refusal gate
# ==========================================================================
@dataclass(frozen=True)
class RetrievalOutcome:
    """Everything the caller — and the audit trail — needs to know about one query.

    `gate_open` is the deterministic refusal decision; when it is False the hits list
    is EMPTY by construction, so no caller can accidentally use sub-gate evidence.
    The raw feature values are carried so `retrieval_runs` can persist why the gate
    decided what it decided — a reviewer must be able to reconstruct the refusal
    (auditability is a product requirement, not a logging nicety).
    """

    hits: list[SearchHit]
    gate_open: bool
    lexical_hit: bool
    vector_top_score: float | None
    vector_peak_gap: float | None
    strategy_version: str
    embedding_model: str | None


def search_hybrid(db: DBSession, *, document_version_id: UUID, query: str,
                  embed_query, limit: int | None = None) -> RetrievalOutcome:
    """Hybrid retrieval within ONE authorized document version, gated.

    ``embed_query`` is a callable ``str -> list[float] | None`` — the store does not
    import the model (the backend is injected), and ``None`` means "no embedding
    available", in which case retrieval degrades to lexical-only with the gate
    honoring the lexical side alone.

    `AM-25` r6 is preserved exactly as in `search_chunks`: the document scope is a
    WHERE clause on the candidate set of BOTH branches, never a post-filter.

    Ranking: reciprocal rank fusion (k=60, the conventional constant) over the
    lexical ranking and the gated vector ranking. Scores shown to callers remain the
    branch-native ones — an RRF sum is a rank artifact and would read as meaning.
    """
    from legalmind.assist.calibration import (
        EVIDENCE_COSINE_FLOOR,
        RETRIEVAL_STRATEGY_VERSION,
        RETRIEVAL_TOP_K,
        gate_is_open,
    )

    limit = limit or RETRIEVAL_TOP_K
    lexical_hits = search_chunks(db, document_version_id=document_version_id,
                                 query=query, limit=limit)

    vector_rows: list = []
    model_identity: str | None = None
    vector = embed_query(query) if embed_query else None
    if vector is not None:
        embedded, model_identity = vector
        schema = config.assist_schema()
        vschema = vector_schema(db)
        vtype = vector_type(db)
        # The cosine-distance OPERATOR lives in the extension's schema exactly as
        # the type does, and unqualified `<=>` does not resolve from the private
        # per-run search_path — hence OPERATOR("schema".<=>).
        op = f'OPERATOR("{vschema}".<=>)'
        literal = "[" + ",".join(f"{x:.6f}" for x in embedded) + "]"
        vector_rows = list(db.execute(text(f"""
            SELECT c.id, c.evidence_id, c.content,
                   e.page_number, e.section_number, e.section_title, e.source_type,
                   1 - (ce.embedding {op} CAST(:q AS {vtype})) AS cosine
              FROM "{schema}".chunk_embeddings ce
              JOIN "{schema}".chunks c ON c.id = ce.chunk_id
              JOIN document_evidence e ON e.id = c.evidence_id
             WHERE c.document_version_id = :dv
             ORDER BY ce.embedding {op} CAST(:q AS {vtype})
             LIMIT :lim
        """), {"q": literal, "dv": document_version_id, "lim": limit}).all())

    scores = [float(r[7]) for r in vector_rows]
    top = scores[0] if scores else None
    gap = (scores[0] - sum(scores[1:]) / len(scores[1:])) if len(scores) > 1 else None
    open_ = gate_is_open(bool(lexical_hits), scores)

    if not open_:
        return RetrievalOutcome(hits=[], gate_open=False,
                                lexical_hit=bool(lexical_hits),
                                vector_top_score=top, vector_peak_gap=gap,
                                strategy_version=RETRIEVAL_STRATEGY_VERSION,
                                embedding_model=model_identity)

    # Individual vector hits below the evidence-inclusion floor are never evidence,
    # gate or no gate. This is deliberately EVIDENCE_COSINE_FLOOR, not the gate's
    # COSINE_FLOOR — the gate has already made its decision above, from the raw
    # `scores` list, before this prune runs. See calibration.py's "Two
    # responsibilities, two constants".
    vector_hits = [
        SearchHit(chunk_id=r[0], evidence_id=r[1], content=r[2], page_number=r[3],
                  section_number=r[4], section_title=r[5], source_type=str(r[6]),
                  retrieval_score=float(r[7]))
        for r in vector_rows if float(r[7]) >= EVIDENCE_COSINE_FLOOR
    ]

    # Reciprocal rank fusion; branch-native score reported (cosine preferred where a
    # chunk appears in both, since it is the more interpretable of the two).
    fused: dict[UUID, float] = {}
    by_id: dict[UUID, SearchHit] = {}
    for rank, hit in enumerate(lexical_hits, start=1):
        fused[hit.chunk_id] = fused.get(hit.chunk_id, 0.0) + 1.0 / (60 + rank)
        by_id.setdefault(hit.chunk_id, hit)
    for rank, hit in enumerate(vector_hits, start=1):
        fused[hit.chunk_id] = fused.get(hit.chunk_id, 0.0) + 1.0 / (60 + rank)
        by_id[hit.chunk_id] = hit   # prefer the cosine-scored representation
    ordered = sorted(fused, key=lambda cid: fused[cid], reverse=True)[:limit]

    return RetrievalOutcome(hits=[by_id[cid] for cid in ordered], gate_open=True,
                            lexical_hit=bool(lexical_hits),
                            vector_top_score=top, vector_peak_gap=gap,
                            strategy_version=RETRIEVAL_STRATEGY_VERSION,
                            embedding_model=model_identity)
