"""escalations

Revision ID: 721650d19741
Revises: 836c18dbc387
Create Date: 2026-08-17 13:47:01.405541
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '721650d19741'
down_revision = '836c18dbc387'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_escalations_finding_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_escalations_raised_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations'))
    )
    op.create_index('ix_escalations_finding_id', 'escalations', ['finding_id'], unique=False)
    op.create_index('ix_escalations_raised_by', 'escalations', ['raised_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_escalations_raised_by', table_name='escalations')
    op.drop_index('ix_escalations_finding_id', table_name='escalations')
    op.drop_table('escalations')
    # ### end Alembic commands ###
