"""initial locked schema

Revision ID: 80dccb65caf6
Revises:
Create Date: 2026-08-17 12:22:59.716111
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '80dccb65caf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permission_group', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', name='config_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements')),
    sa.UniqueConstraint('code', name=op.f('uq_requirements_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_actor_id', 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_timestamp', 'audit_events', ['timestamp'], unique=False)
    op.create_table('configuration_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_hash', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_configuration_snapshots_created_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_snapshots')),
    sa.UniqueConstraint('snapshot_hash', name=op.f('uq_configuration_snapshots_snapshot_hash'))
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', name='contract_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_contracts_owner_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_index('ix_contracts_created_at', 'contracts', ['created_at'], unique=False)
    op.create_index('ix_contracts_owner_id', 'contracts', ['owner_id'], unique=False)
    op.create_index('ix_contracts_status', 'contracts', ['status'], unique=False)
    op.create_table('requirement_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evaluator_type', sa.Enum('NUMERIC_COMPARISON', 'PRESENCE', name='evaluator_type'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_requirement_versions_created_by')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_versions_requirement_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_versions')),
    sa.UniqueConstraint('requirement_id', 'version_number', name='uq_requirement_versions_requirement_version')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('OIDC', 'PASSWORD', name='identity_provider'), nullable=False),
    sa.Column('provider_subject', sa.String(), nullable=True),
    sa.Column('credential_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_user_identities_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_identities_user_provider')
    )
    op.create_index('ix_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('company_standard_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_version_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_company_standard_versions_created_by')),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], name=op.f('fk_company_standard_versions_requirement_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_standard_versions')),
    sa.UniqueConstraint('requirement_version_id', 'version_number', name='uq_company_standard_versions_reqver_version')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processing_status'), nullable=False),
    sa.Column('extraction_status', sa.Enum('COMPLETE', 'PARTIAL', 'AMBIGUOUS', 'FAILED', name='extraction_status'), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_document_versions_contract_id')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('contract_id', 'version_number', name='uq_document_versions_contract_version')
    )
    op.create_index('ix_document_versions_contract_id', 'document_versions', ['contract_id'], unique=False)
    op.create_index('ix_document_versions_file_hash', 'document_versions', ['file_hash'], unique=False)
    op.create_index('ix_document_versions_processing_status', 'document_versions', ['processing_status'], unique=False)
    op.create_index('ix_document_versions_uploaded_by', 'document_versions', ['uploaded_by'], unique=False)
    op.create_table('evaluation_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_version_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('evaluator_type', sa.Enum('NUMERIC_COMPARISON', 'PRESENCE', name='evaluator_type'), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_evaluation_rule_versions_created_by')),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], name=op.f('fk_evaluation_rule_versions_requirement_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_rule_versions')),
    sa.UniqueConstraint('requirement_version_id', 'version_number', name='uq_evaluation_rule_versions_reqver_version')
    )
    op.create_table('legal_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_version_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('THRESHOLD', 'ALLOWED_VALUES', 'PRESENCE', name='rule_type'), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_legal_rule_versions_created_by')),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], name=op.f('fk_legal_rule_versions_requirement_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_rule_versions')),
    sa.UniqueConstraint('requirement_version_id', 'version_number', name='uq_legal_rule_versions_reqver_version')
    )
    op.create_table('mapping_rule_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requirement_version_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mapping_rule_versions_created_by')),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], name=op.f('fk_mapping_rule_versions_requirement_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_rule_versions')),
    sa.UniqueConstraint('requirement_version_id', 'version_number', name='uq_mapping_rule_versions_reqver_version')
    )
    op.create_table('configuration_snapshot_items',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('requirement_version_id', sa.UUID(), nullable=False),
    sa.Column('company_standard_version_id', sa.UUID(), nullable=False),
    sa.Column('legal_rule_version_id', sa.UUID(), nullable=True),
    sa.Column('mapping_rule_version_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_rule_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_standard_version_id'], ['company_standard_versions.id'], name=op.f('fk_configuration_snapshot_items_company_standard_version_id')),
    sa.ForeignKeyConstraint(['evaluation_rule_version_id'], ['evaluation_rule_versions.id'], name=op.f('fk_configuration_snapshot_items_evaluation_rule_version_id')),
    sa.ForeignKeyConstraint(['legal_rule_version_id'], ['legal_rule_versions.id'], name=op.f('fk_configuration_snapshot_items_legal_rule_version_id')),
    sa.ForeignKeyConstraint(['mapping_rule_version_id'], ['mapping_rule_versions.id'], name=op.f('fk_configuration_snapshot_items_mapping_rule_version_id')),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], name=op.f('fk_configuration_snapshot_items_requirement_version_id')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['configuration_snapshots.id'], name=op.f('fk_configuration_snapshot_items_snapshot_id')),
    sa.PrimaryKeyConstraint('snapshot_id', 'requirement_version_id', name=op.f('pk_configuration_snapshot_items'))
    )
    op.create_table('document_processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('PARSE', 'OCR', 'REPROCESS', name='processing_run_type'), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', name='processing_run_status'), nullable=False),
    sa.Column('processor_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_processing_runs_document_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_processing_runs'))
    )
    op.create_index('ix_document_processing_runs_created_at', 'document_processing_runs', ['created_at'], unique=False)
    op.create_index('ix_document_processing_runs_document_version_id', 'document_processing_runs', ['document_version_id'], unique=False)
    op.create_index('ix_document_processing_runs_status', 'document_processing_runs', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('configuration_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UPLOADED', 'PROCESSING', 'ANALYSIS_COMPLETE', 'LEGAL_REVIEW', 'RESOLVED', 'CLOSED', 'ANALYSIS_FAILED', 'CANCELLED', name='review_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['configuration_snapshot_id'], ['configuration_snapshots.id'], name=op.f('fk_reviews_configuration_snapshot_id')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_reviews_contract_id')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reviews_created_by')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_reviews_document_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index('ix_reviews_contract_id', 'reviews', ['contract_id'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_created_by', 'reviews', ['created_by'], unique=False)
    op.create_index('ix_reviews_document_version_id', 'reviews', ['document_version_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_table('document_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_number', sa.String(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('NATIVE_TEXT', 'OCR', 'TABLE', 'OTHER', name='evidence_source_type'), nullable=False),
    sa.Column('start_offset', sa.BigInteger(), nullable=True),
    sa.Column('end_offset', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_evidence_document_version_id')),
    sa.ForeignKeyConstraint(['processing_run_id'], ['document_processing_runs.id'], name=op.f('fk_document_evidence_processing_run_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_evidence'))
    )
    op.create_index('ix_document_evidence_document_version_id', 'document_evidence', ['document_version_id'], unique=False)
    op.create_index('ix_document_evidence_docver_page', 'document_evidence', ['document_version_id', 'page_number'], unique=False)
    op.create_index('ix_document_evidence_processing_run_id', 'document_evidence', ['processing_run_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('requirement_version_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('MATCH', 'DEVIATION', 'MISSING', 'CONFLICT', 'AMBIGUOUS', 'UNRESOLVED', 'UNABLE_TO_EVALUATE', name='finding_classification'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DECISION_REQUIRED', 'AWAITING_CLARIFICATION', 'RESOLVED', name='finding_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_version_id'], ['requirement_versions.id'], name=op.f('fk_findings_requirement_version_id')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_findings_review_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('review_id', 'requirement_version_id', name='uq_findings_review_requirement_version')
    )
    op.create_index('ix_findings_review_id', 'findings', ['review_id'], unique=False)
    op.create_index('ix_findings_status', 'findings', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_type', sa.Enum('NUMERIC_COMPARISON', 'PRESENCE', name='evaluator_type'), nullable=False),
    sa.Column('evaluator_version', sa.String(), nullable=False),
    sa.Column('scope_key', sa.String(), nullable=False),
    sa.Column('scope_label', sa.String(), nullable=True),
    sa.Column('evaluation_kind', sa.Enum('PRIMARY', 'EXCEPTION', name='evaluation_kind'), nullable=False),
    sa.Column('classification', sa.Enum('MATCH', 'DEVIATION', 'MISSING', 'CONFLICT', 'AMBIGUOUS', 'UNRESOLVED', 'UNABLE_TO_EVALUATE', name='finding_classification'), nullable=False),
    sa.Column('rule_outcome', sa.Enum('ACCEPTABLE', 'APPROVAL_REQUIRED', 'UNACCEPTABLE', 'NOT_APPLICABLE', name='rule_outcome'), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('legal_rule_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_evaluations_finding_id')),
    sa.ForeignKeyConstraint(['legal_rule_version_id'], ['legal_rule_versions.id'], name=op.f('fk_evaluations_legal_rule_version_id')),
    sa.ForeignKeyConstraint(['rule_version_id'], ['evaluation_rule_versions.id'], name=op.f('fk_evaluations_rule_version_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('id', 'finding_id', name='uq_evaluations_id_finding_id')
    )
    op.create_index('ix_evaluations_finding_id', 'evaluations', ['finding_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PRIMARY', 'SUPPORTING', 'CONFLICTING', name='evidence_relationship_type'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['document_evidence.id'], name=op.f('fk_finding_evidence_evidence_id')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_evidence_finding_id')),
    sa.PrimaryKeyConstraint('finding_id', 'evidence_id', name=op.f('pk_finding_evidence'))
    )
    op.create_table('unmatched_provisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['document_evidence.id'], name=op.f('fk_unmatched_provisions_evidence_id')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_unmatched_provisions_review_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unmatched_provisions')),
    sa.UniqueConstraint('review_id', 'evidence_id', name='uq_unmatched_provisions_review_evidence')
    )
    op.create_table('evaluation_evidence',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PRIMARY', 'SUPPORTING', 'CONFLICTING', name='evidence_relationship_type'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_evaluation_evidence_evaluation_id')),
    sa.ForeignKeyConstraint(['evidence_id'], ['document_evidence.id'], name=op.f('fk_evaluation_evidence_evidence_id')),
    sa.PrimaryKeyConstraint('evaluation_id', 'evidence_id', name=op.f('pk_evaluation_evidence'))
    )
    op.create_table('legal_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.Enum('ACCEPT_DEVIATION', 'REQUIRE_COMPANY_STANDARD', 'APPROVE_CUSTOMIZATION', 'REJECT', 'REQUEST_CLARIFICATION', name='decision_type'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_legal_decisions_decided_by')),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], name=op.f('fk_legal_decisions_evaluation_id')),
    sa.ForeignKeyConstraint(['finding_id', 'evaluation_id'], ['evaluations.finding_id', 'evaluations.id'], name='fk_legal_decisions_evaluation_same_finding'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_legal_decisions_finding_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_decisions')),
    sa.UniqueConstraint('evaluation_id', 'version_number', name='uq_legal_decisions_evaluation_version')
    )
    op.create_index('ix_legal_decisions_created_at', 'legal_decisions', ['created_at'], unique=False)
    op.create_index('ix_legal_decisions_decided_by', 'legal_decisions', ['decided_by'], unique=False)
    op.create_index('ix_legal_decisions_evaluation_version', 'legal_decisions', ['evaluation_id', 'version_number'], unique=False)
    # ### end Alembic commands ###




    # ------------------------------------------------------------------
    # EV-MIN — every Finding has >= 1 Evaluation (AB-1.6, invariant D-3.4).
    #
    # Enforced by a DEFERRABLE INITIALLY DEFERRED constraint trigger so the
    # check happens at COMMIT and insert order inside the transaction does not
    # matter. Chosen over a service-layer invariant because EV-MIN is
    # load-bearing (legal_decisions.evaluation_id NOT NULL depends on it) and a
    # migration or backfill can bypass service code.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION legalmind_check_ev_min() RETURNS trigger AS $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM evaluations WHERE finding_id = NEW.id
            ) THEN
                RAISE EXCEPTION
                    'EV-MIN violated: finding % has no evaluation', NEW.id
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE CONSTRAINT TRIGGER trg_findings_ev_min
        AFTER INSERT ON findings
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION legalmind_check_ev_min();
    """)

    # ------------------------------------------------------------------
    # Append-only enforcement (AUD-01; Step 31 r14).
    #
    # audit_events and legal_decisions are historical legal records. Blocking
    # UPDATE/DELETE in the database means no application bug, migration or
    # manual script can rewrite legal history.
    # ------------------------------------------------------------------
    op.execute("""
        CREATE OR REPLACE FUNCTION legalmind_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                '% is append-only; % is not permitted', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
    """)
    for _table in ("audit_events", "legal_decisions"):
        op.execute(
            f"CREATE TRIGGER trg_{_table}_append_only "
            f"BEFORE UPDATE OR DELETE ON {_table} "
            f"FOR EACH ROW EXECUTE FUNCTION legalmind_append_only();"
        )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_legal_decisions_append_only ON legal_decisions")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS legalmind_append_only()")
    op.execute("DROP TRIGGER IF EXISTS trg_findings_ev_min ON findings")
    op.execute("DROP FUNCTION IF EXISTS legalmind_check_ev_min()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_decisions_evaluation_version', table_name='legal_decisions')
    op.drop_index('ix_legal_decisions_decided_by', table_name='legal_decisions')
    op.drop_index('ix_legal_decisions_created_at', table_name='legal_decisions')
    op.drop_table('legal_decisions')
    op.drop_table('evaluation_evidence')
    op.drop_table('unmatched_provisions')
    op.drop_table('finding_evidence')
    op.drop_index('ix_evaluations_finding_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('ix_findings_status', table_name='findings')
    op.drop_index('ix_findings_review_id', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_document_evidence_processing_run_id', table_name='document_evidence')
    op.drop_index('ix_document_evidence_docver_page', table_name='document_evidence')
    op.drop_index('ix_document_evidence_document_version_id', table_name='document_evidence')
    op.drop_table('document_evidence')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_document_version_id', table_name='reviews')
    op.drop_index('ix_reviews_created_by', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_reviews_contract_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_document_processing_runs_status', table_name='document_processing_runs')
    op.drop_index('ix_document_processing_runs_document_version_id', table_name='document_processing_runs')
    op.drop_index('ix_document_processing_runs_created_at', table_name='document_processing_runs')
    op.drop_table('document_processing_runs')
    op.drop_table('configuration_snapshot_items')
    op.drop_table('mapping_rule_versions')
    op.drop_table('legal_rule_versions')
    op.drop_table('evaluation_rule_versions')
    op.drop_index('ix_document_versions_uploaded_by', table_name='document_versions')
    op.drop_index('ix_document_versions_processing_status', table_name='document_versions')
    op.drop_index('ix_document_versions_file_hash', table_name='document_versions')
    op.drop_index('ix_document_versions_contract_id', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('company_standard_versions')
    op.drop_table('user_roles')
    op.drop_index('ix_user_identities_user_id', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_table('requirement_versions')
    op.drop_index('ix_contracts_status', table_name='contracts')
    op.drop_index('ix_contracts_owner_id', table_name='contracts')
    op.drop_index('ix_contracts_created_at', table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('configuration_snapshots')
    op.drop_index('ix_audit_events_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('requirements')
    op.drop_table('permissions')
    # ### end Alembic commands ###
    # Native enum types are not dropped automatically by table drops;
    # leaving them behind makes a subsequent upgrade fail with
    # DuplicateObject. Downgrade must return the database to a state a
    # fresh upgrade can run against (Step 55.4).
    for _enum_type in (
        "user_status",
        "contract_status",
        "config_status",
        "processing_status",
        "extraction_status",
        "processing_run_type",
        "processing_run_status",
        "evidence_source_type",
        "rule_type",
        "identity_provider",
        "review_status",
        "finding_status",
        "finding_classification",
        "rule_outcome",
        "decision_type",
        "evaluator_type",
        "evaluation_kind",
        "evidence_relationship_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum_type} CASCADE")
