"""review assignments

Revision ID: 836c18dbc387
Revises: 80dccb65caf6
Create Date: 2026-08-17 12:43:06.201386
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '836c18dbc387'
down_revision = '80dccb65caf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_review_assignments_assigned_by')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_assignments_review_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_assignments_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_assignments')),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_assignments_review_user')
    )
    op.create_index('ix_review_assignments_review_id', 'review_assignments', ['review_id'], unique=False)
    op.create_index('ix_review_assignments_user_id', 'review_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_assignments_user_id', table_name='review_assignments')
    op.drop_index('ix_review_assignments_review_id', table_name='review_assignments')
    op.drop_table('review_assignments')
    # ### end Alembic commands ###
